package publication_quality_system.enums;

public enum PermissionName {
    USER_CREATE, USER_READ, USER_UPDATE, USER_DELETE,
    ROLE_CREATE, ROLE_READ, ROLE_UPDATE, ROLE_DELETE, ROLE_ASSIGN,
    RESEARCH_GROUP_CREATE, RESEARCH_GROUP_READ, RESEARCH_GROUP_UPDATE, RESEARCH_GROUP_DELETE,
    RESEARCH_GROUP_MEMBER_MANAGE,
    RESEARCH_PROFILE_CREATE, RESEARCH_PROFILE_READ, RESEARCH_PROFILE_UPDATE, RESEARCH_PROFILE_DELETE,
    LAB_MEMBER_CREATE, LAB_MEMBER_READ, LAB_MEMBER_UPDATE, LAB_MEMBER_DELETE,
    PAPER_CREATE, PAPER_READ_OWN, PAPER_READ_ALL, PAPER_UPDATE_OWN, PAPER_UPDATE_ALL,
    PAPER_DELETE_OWN, PAPER_DELETE_ALL, PAPER_SUBMIT_INTERNAL_REVIEW,
    PAPER_VERSION_UPLOAD, PAPER_VERSION_READ, PAPER_VERSION_COMPARE, PAPER_VERSION_DELETE,
    QUALITY_CHECK_RUN, QUALITY_REPORT_READ,
    INTEGRITY_CHECK_RUN, INTEGRITY_REPORT_READ_OWN, INTEGRITY_REPORT_READ_ALL, INTEGRITY_REPORT_APPROVE,
    REVIEW_CREATE, REVIEW_READ_ASSIGNED, REVIEW_READ_ALL, REVIEW_ASSIGN, REVIEW_DECISION_SUBMIT,
    VENUE_RECOMMEND, VENUE_CREATE, VENUE_UPDATE, VENUE_DELETE,
    SUBMISSION_CREATE, SUBMISSION_UPDATE, SUBMISSION_TRACK, SUBMISSION_APPROVE,
    REVIEWER_RESPONSE_CREATE, REVIEWER_RESPONSE_READ,
    NOTIFICATION_READ, NOTIFICATION_MANAGE,
    ANALYTICS_READ_OWN, ANALYTICS_READ_LAB, ANALYTICS_READ_ALL,
    KNOWLEDGE_BASE_CREATE, KNOWLEDGE_BASE_READ, KNOWLEDGE_BASE_UPDATE, KNOWLEDGE_BASE_DELETE,
    ADMIN_SETTING_MANAGE,
    AUDIT_LOG_READ
}
